FROM hub.17usoft.com/base/nodejs:18.14.2

RUN sed -i 's#http://deb.debian.org#http://mirrors.cloud.tencent.com#g;s#http://security.debian.org#http://mirrors.cloud.tencent.com#g' /etc/apt/sources.list \
    && npm c set registry="https://registry.npmmirror.com"


# 更新包列表并安装必要的软件包
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates

    # 更新包列表并安装 lsof
RUN apt-get install -y lsof

# 清理无用的文件
RUN apt-get clean && rm -rf /var/lib/apt/lists/*